// Compact grid data
const compact = [
  ["Dart","Flutter apps, mobile & web UI"],["Scala","JVM language: functional + OOP, big-data (Spark)"],
  ["Perl","Text processing, scripting"],["Lua","Lightweight scripting, game scripting (embedded)"],
  ["Haskell","Pure functional, strong types, research"],["Objective-C","Legacy iOS/macOS codebase"],
  ["Shell (Bash)","Scripting/automation on UNIX systems"],["Julia","High-performance numerical computing"],
  ["F#","Functional-first .NET language"],["Solidity","Smart contracts on Ethereum"],
  ["VHDL / Verilog","Hardware description languages for FPGAs/ASICs"],["Fortran","Scientific computing legacy but still used"],
  ["COBOL","Enterprise legacy systems in finance/government"],["Erlang / Elixir","Fault-tolerant distributed systems (telecoms, messaging)"],
  ["Groovy","JVM scripting, Gradle scripts"],["Ada","Safety-critical aerospace & defense"],
  ["Prolog","Logic programming, AI research"],["Lisp / Clojure","Homoiconicity, macros, AI history"]
];

// Inject compact grid
const compactGrid = document.getElementById('compactGrid');
compact.forEach(item => {
  const col = document.createElement('div');
  col.className = 'col-6 col-md-4 col-lg-3';
  col.innerHTML = `<article class="p-2 glass-card language-card h-100" onclick="fetchText('${item[0]}')">
    <div class="d-flex justify-content-between align-items-start"><strong>${item[0]}</strong><small class="lang-meta">quick</small></div>
    <p class="mb-0 small">${item[1]}</p></article>`;
  compactGrid.appendChild(col);
});

// Search functionality
const filterCards = () => {
  const q = document.getElementById('searchInput').value.trim().toLowerCase();
  document.querySelectorAll('.language-item').forEach(item => {
    const match = (item.getAttribute('data-tags') || '').includes(q) || (item.innerText || '').toLowerCase().includes(q);
    item.style.display = !q || match ? 'block' : 'none';
  });
};
document.getElementById('searchInput').addEventListener('input', filterCards);
document.getElementById('resetBtn').addEventListener('click', () => { document.getElementById('searchInput').value = ''; filterCards(); });

// Scalable Text File Fetcher & Modal
async function fetchText(course) {
  document.getElementById('modalTitle').innerText = course + " Roadmap";
  document.getElementById('modalContent').innerText = "Loading static file...";
  document.getElementById('textModal').style.display = 'flex';

  try {
    // Fetching the plain text file generated by syncData.js
    const res = await fetch(`data/${course}.txt`);
    document.getElementById('modalContent').innerText = res.ok ? await res.text() : "File not found. Run syncData.js first.";
  } catch (e) {
    document.getElementById('modalContent').innerText = "Error loading file.";
  }
}

const closeModal = () => document.getElementById('textModal').style.display = 'none';

// Add click events to main grid cards dynamically
document.querySelectorAll('#langGrid > .language-item .language-card').forEach(card => {
  card.onclick = () => fetchText(card.querySelector('h5').innerText);
});

window.addEventListener('load', () => document.getElementById('searchInput').focus());